# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 448cc9e0cf8d75a5d3effc767e4ae1877d33d32d5fc43306d654dcac55248b1810c23994826082e577077cdc4ea6f785c4eca2b0b2b5d9b0ec0cfa84e82e2f8e

test:
  secret_key_base: d44168f66f95266255ed5af7b932698957d6ebb2168d6708e13c0de529c7f26d968a987b96afc02ec9724b82d31fbad4df3fe3852f0f8945cba2b5136daab2b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
